# data gathered from the hardware doesn't check if the row has finished printing before saving the values
# as such the first and last row of the gathered data tends to be invalid
# this code creates a clean csv file for every raw txt file generated by the hardware setup

import csv
import os

# search folder for all files
path = "filter_final"
files_in_folder = os.listdir(path)

for file in files_in_folder:
    # only mess with the txt files
    if ".txt" in file:
        # create csv file
        file_name = path + "/" + file
        with open(file_name, "r") as file_data:
            lines = file_data.readlines()
            # remove first and last line
            lines = lines[1:-1]

            # write to new file
            output_file_name = file_name[:-4] + ".csv"
            with open(output_file_name, "w", newline='') as output_file:
                csv_writer = csv.writer(output_file, delimiter=",")
                for line in lines:
                    csv_writer.writerow(line.strip().split(","))

